/*
 * Ski Data API for NEU Seattle distributed systems course
 *
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * API version: 1.16
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LiftRide struct {

	Time int32 `json:"time,omitempty"`

	LiftID int32 `json:"liftID,omitempty"`

	WaitTime int32 `json:"waitTime,omitempty"`
}
